SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio, precio * 1.1 AS precio_usd FROM producto;
SELECT nombre AS "producto", precio AS "euros", precio * 1.1 AS "dolares" FROM producto;
SELECT UPPER(nombre) AS "producto" , precio FROM producto;
SELECT LOWER(nombre) AS "producto", precio FROM producto;
SELECT nombre AS "nombre fabricante", UPPER(SUBSTRING(nombre, 1, 2)) as "dos primeros caracteres del fabricante" FROM fabricante;
SELECT nombre AS "producto", ROUND(precio) as "precio redondeado" FROM producto;
SELECT nombre AS "producto", TRUNCATE(precio, 0) AS "precio sin decimales" FROM producto;
SELECT codigo_fabricante FROM producto;
SELECT DISTINCT codigo_fabricante FROM producto;
SELECT nombre AS "nombre fabricante" FROM fabricante ORDER BY nombre ASC;
SELECT nombre AS "nombre fabricante" FROM fabricante ORDER BY nombre DESC;
SELECT nombre as "nombre producto", precio FROM producto ORDER BY nombre ASC, precio DESC;
SELECT * FROM fabricante LIMIT 5;
SELECT * FROM fabricante LIMIT 2 OFFSET 3;
SELECT nombre as "nombre producto", precio FROM producto ORDER BY precio ASC LIMIT 1;
SELECT nombre AS "nombre producto", precio FROM producto ORDER BY precio DESC LIMIT 1;
SELECT nombre FROM producto WHERE codigo_fabricante = 2;
SELECT p.nombre AS "producto", p.precio, f.nombre AS "fabricante" FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;
SELECT p.nombre, p.precio, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo ORDER BY f.nombre ASC;
SELECT p.codigo, p.nombre, p.codigo_fabricante, f.nombre FROM producto p JOIN fabricante f ON p.codigo_fabricante = f.codigo;